### ISSUE TITLE
Can't this script parse windows Skype indexeddb

### ISSUE THREAD

**Issue by idiotc4t** [megabyte0/skype_leveldb#1]
Can't this script parse windows Skype indexeddb

**Comment by megabyte0** [comment]
Thank you, now it can, tested with windows7 `%appdata%\Roaming\Microsoft\Skype for Desktop\IndexedDB\file__0.indexeddb.leveldb`. Now it requires the third parameter -- encoding codepage, when working with windows skype leveldb, because of `\xc9` 'copyright' character in the `"` strings somewhere. See commit [bf41295](https://github.com/megabyte0/skype_leveldb/commit/bf41295d2185315f475b45d6b8e22d6e17c3b1b6). I would be thankful if you kindly let me know if it works now. Thanks. )
